- targets/windows.go
The platform passed in to the `Windows` target function ends up being "windows/\<arch\>", which when used as the container platform results in a manifest retrieval error; these images aren't available for windows.
> Fix windows build container

- testutil/qemu.go
This kernel is used inside the test VM.
Before this change the install is broken due to updated versions of these pacakges being released and Canonical removes the older packages from the repo. Now it just installs what's there.
> Fix qemu kernel install

- moby-runc/deb.mk
- moby-runc/rpm.mk
This was not getting set before because the runc build scripts always read from the `VERSION` file in the repo source.
Closes #52
> runc: set version on runc binary

- distros_test.go
- package_test.go
- pkg/archive/deb.go
- pkg/archive/rpm.go
- tests/mariner2/install.sh
- tests/test_runner.sh
- do not copy installer scripts to test vm rootfs (scp at runtime instead)
- use dnf in mariner installer script
- Do not automatically apply +azure to package names
- Move test img setup behind interfaces and fix version formatting issues for the test's expected version
I recommend going through this commit by commit
> Various test fixes simplifications

- moby-tini/mapping.go
This is required because versions of moby-engine prior to v24.0.0 will install `docker-init`, which will also be installed by moby-tini. Introducing this conflict prevents both from being installed.
> packages: tini conflicts with moby-engine < 24

- Makefile
- moby-tini/mapping.go
- tests/test.sh
Starting with docker v24 dockerd will lookup docker-init in more than just $PATH, including /usr/libexec/docker/*.
Moving it here is both more "correct" in terms of linux userspace layout, but also gets us away from needing to mark moby-engine < 24 as conflicting.
> Move docker-init to /usr/libexec/docker/

- queue_consumer.yaml
Check the queue two hours after the build is triggered.
> pipeline: Enable queue consumer cron job

- cmd/pop/main.go
- queue_consumer.yaml
There was a subtle bug in the error handling closure. The `err` variable from the environment was being captured and appended to the errs array. That variable was always nil, so no errors were being captured.
There was also a problem where the pipeline was improperly surfacing errors. This is because the payload is now base64 encoded. The surfacing code has been adjusted accordingly.
> queue: fix error handling

- queue_consumer.yaml
Otherwise, the deduplication-after-dequeue is flawed. If we only pull 30 messages, we are only resolving duplicates within those 30. We want to resolve all duplicates.
> queue: dequeue all messages

- pipeline.yml
Engine tests won't work if it can't get moby-tini. When we changed the directory layout to include the intervening os_arch directory, I forgot to change this to reflect the directory structure.
> pipeline: fix integration tests for moby-engine on mariner

- cmd/pop/main.go
- cmd/push/main.go
- make.go
- pipeline.yml
The latest api determines the listed architecture by performing a series of transformations. For example, `linux_amd64` would be split by the `_` delimiter, with `"linux"` as the os, `"amd64"` as the architecture, and `null` as the variant. The variant is `null` because there is no third element when splitting by `_`.
However, when the directory containing the artifact is named `linux_armv7` (as the code prior to this commit did), then the variant will still be `null`, whereas we want the variant to be `"v7"`. The variant is used by the latest API to assemble the architecture listing.
Existing listings have been `"arm/v7"`, and this change will return consistency to the listed architecture of armv7 packages.
> build: Fix output directory structure

- queue_consumer.yaml
Query the API to cancel the build. Set the buildnumber to note that there are no new messages (but retain build ID prefix).
This will prevent us from needing to manually approve or cancel when there are no messages to process.
> Prevent next stages from running when queue empty

- cmd/pop/main.go
- pkg/queue/message.go
- queue_consumer.yaml
*relevant diff here:* https://github.com/Azure/moby-packaging/compare/skip_when_no_messages...dequeue_all_messages
*note* this PR is based on #96, and that PR should be merged first.
- Move message fetching to go program
- Fetch all messages before proceeding, instead of a batch of 32
> Dequeue all messages

- moby-buildx/mapping.go
- targets/go.go
Also bumps go to 1.20 which is a new minimum requirement for buildx.
> Add conflict for docker-buildx-plugin

- scripts/min-versions.json
This will create an index for `moby-containerd-shim-systemd` so that it can be queried via the PMC latest API.
> Add shim to min-versions.json

- pkg/archive/deb.go
There were two bugs fixed here.
1. The post-upgrade action was not being handled at all (it was grouped with the post-install action)
2. There was a subtle bug in our script template. Because `fpm` wraps postinstall scripts in a function, the references to `$1` in our generated templates will refer to the first argument of the wrapping function, and not the first argument of the script as intended. Because the logic of when to run the scripts is handled by fpm, we need not reference positional script arguments at all.
> Fix install scripts for debian-based packages

- pipeline.yml
`+x` and `-x` were mistakenly being used in place of `+e` and `-e`. This results in suppressing command expansion, but still exits if the tests fail. We want to upload the test results in the event of test failures!
> Fix test result upload

- pipeline.yml
This makes it so we don't need to have a manual step to sync packages to PMC.
In the future I'd like to move these out of an ADO pipeline trigger, but this is the path of least resistance for now.
> Trigger PMC package uploads

- go.mod
- go.sum
- make.go
- moby-buildx/go_version.go
- moby-cli/go_version.go
- moby-compose/go_version.go
- moby-containerd-shim-systemd/go_version.go
- moby-containerd/go_version.go
- moby-engine/go_version.go
- moby-runc/go_version.go
- moby-tini/go_version.go
- moby-tini/mapping.go
- pkg/goversion/version.go
- targets/bionic.go
- targets/bookworm.go
- targets/bullseye.go
- targets/buster.go
- targets/centos7.go
- targets/focal.go
- targets/go.go
- targets/jammy.go
- targets/mariner2.go
- targets/rhel8.go
- targets/rhel9.go
- targets/target.go
- targets/windows.go
This is required for building moby-compose 2.22
> Bump go version to 1.21.1 for go container

- targets/target.go
The global `GoRef` has been removed, so the code will not compile as-is.
> Fix rebase error

- pipeline.yml
The PMC sync pipeline is in the `pipelines` repo, which has a `master` branch, not `main`.
> Use PMC pipeline 'master' branch

- moby-buildx/go_version.go
This is now used upstream for v0.12.
> buildx: use go1.21

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- pkg/goversion/version.go
- targets/target_test.go
- Bump go versions
- Fix broken test
- Add CI workflow to actually run unit tests
- Bump CodeQL actions for go1.21 support
- Remove autobuild since it is not needed and is broken
> A few fixups

- moby-engine/systemd/docker.service
This was a change made upstream due to the value of `infinity` being too high for certain workloads + host kernels.
The way systemd sets up the defaults now are perfectly fine these days.
> Remove LimitNOFILE=infinity from engine unit file

- packages/moby-containerd/deb.mk
Currently, containerd 1.6 is unbuildable without the module proxy due to the github.com/mitchellh/osext depdency being taken down from github. This dependency is a transient depdendency in containerd 1.6.
> containerd: use the go module proxy

- packages/moby-containerd/rpm.mk
ref: https://github.com/containerd/containerd/issues/9969
> containerd: Also use go module proxy in the rpm build

- make.go
- packages/moby-compose/go_version.go
- packages/moby-containerd/mapping.go
- packages/moby-containerd/mapping_1_6.go
- packages/moby-containerd/mapping_2_0.go
- targets/target.go
The main difference here is 2.0 drops support for the v1 shim (`containerd-shim` and `containerd-shim-runc-v1`) binaries. But we still need to support building 1.x packages for now so this splits those up into "archives".
When building we do a switch on the version tag to determine which set of archives to use.
> Add support for building containerd 2.0

- packages/moby-containerd/mapping_1_6.go
- packages/moby-containerd/mapping_2_0.go
This was caused by a bad copy/paste when adding the 2.0 builds. Fixed the problem and also moved jammy up with the rest of the ubuntu versions so they are better grouped.
> containerd: Fix incorrect archive reference for 1.x builds

- pkg/goversion/version.go
This addresses multiple CVE's in go.
> Bump go version to 1.21.10

- packages/moby-containerd/go_version.go
I tested this using a different version format than what we actually use in our builds.
Since the tag field is used for package versions, the version is not semver compatible due to the use of `~` for prerelease versions.
This just drops the tilde and everything after since this is not something we care about when checking the version.
> Fix go version switch for containerd

- cmd/run_tests/main.go
- packages/moby-runc/deb.mk
Upstream changed how the binary version can be set which broke how we were setting it.
Now we can pass a VERSION env var into runcs make file to have it use that instead of modifying the VERSION file in the repo.
Because we already have a VERSION field set in the env, the runc makefile is taking that, but it does not contain the revision number, so we need to modify that env.
Upstream change that broke this is https://github.com/opencontainers/runc/pull/4270
> runc: fix how version is set after upstream change

- packages/moby-runc/rpm.mk
The last fix only did debs (oops).
This takes care of it for rpms.
> runc: fix runc version for rpms

- packages/moby-buildx/go_version.go
- packages/moby-compose/go_version.go
- packages/moby-containerd/go_version.go
- pkg/goversion/version.go
go1.21 is EOL
go1.22 should be able to be used everywhere except compose which requires go1.23.
> Bump go versions

- packages/moby-runc/deb.mk
- packages/moby-runc/rpm.mk
The makefile for runc no longer supports setting COMMIT (and some other things) through env var and instead must be set through make args.
Additionally adds `urfave_cli_no_docs` which is added to the base BUILDTAGS in 1.2 but is not set in 1.1.
This just makes it so the build tag is set on both 1.1 and 1.2 instead of relying on the make file for those tags across branches.
> runc: set COMMIT via make arg

- tests/Dockerfile
- tests/Makefile
- tests/deb/install.sh
This just uses apt-ftparchive which simplifies a lot of the test setup.
> Remove use of aptly

- pkg/goversion/version.go
This is the minimal change to get compose to continue to build. We'll need to bump to 1.24 soon, but for now 1.23 is fine.
> Bumps to latest 1.23 release version
